M48
; DRILL file {KiCad (6.0.2)} date Sat Feb 11 22:38:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-11T22:38:05+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X79.445Y-29.0
X79.445Y-60.0
X125.165Y-29.0
X125.165Y-60.0
X169.445Y-29.0
X169.445Y-60.0
T0
M30
